'use strict';
// Skills graph page. Loads data/graph.json (generated by scripts/build_graph.py),
// renders it with Cytoscape.js, filters by family, and shows node details on click.
// The pure functions at the top are exported for Node tests (scripts/test_app.cjs).

const FAMILY_PREFIX = 'family:';

// Node color by kind: the first three colors of d3's category10 scheme, a common
// default for telling categories apart. Not a designed palette.
const KIND_COLORS = { skill: '#1f77b4', agent: '#ff7f0e', hook: '#2ca02c' };
// A node whose own SKILL.md states an eval score gets this outline.
const MEASURED_OUTLINE = { width: 4, color: '#000000' };
const LABEL_FONT_SIZE = 17;

function isMeasured(n) {
  return typeof n.eval_status === 'string' && n.eval_status.startsWith('measured:');
}

// Zero-width spaces after hyphens let long names wrap at hyphens.
function nodeLabel(name) {
  return String(name).replace(/-/g, '-\u200b');
}

function checkGraph(graph) {
  const ok =
    graph &&
    Array.isArray(graph.families) &&
    Array.isArray(graph.nodes) &&
    Array.isArray(graph.edges) &&
    graph.nodes.every((n) => n && typeof n.id === 'string' && typeof n.family === 'string') &&
    graph.edges.every((e) => e && typeof e.id === 'string' && typeof e.source === 'string' && typeof e.target === 'string');
  if (!ok) throw new Error('graph.json does not have families[], nodes[], and edges[] in the expected shape');
  const ids = new Set(graph.nodes.map((n) => n.id));
  const families = new Set(graph.families.map((f) => f.id));
  const all = [...graph.nodes.map((n) => n.id), ...graph.edges.map((e) => e.id), ...graph.families.map((f) => FAMILY_PREFIX + f.id)];
  const seen = new Set();
  for (const id of all) {
    if (seen.has(id)) throw new Error(`duplicate id ${id}`);
    seen.add(id);
  }
  for (const n of graph.nodes) {
    if (!families.has(n.family)) throw new Error(`node ${n.id} has unknown family ${n.family}`);
    if (!(n.kind in KIND_COLORS)) throw new Error(`node ${n.id} has unknown kind ${n.kind}`);
  }
  for (const e of graph.edges) {
    if (!ids.has(e.source) || !ids.has(e.target)) throw new Error(`edge ${e.id} has a missing endpoint`);
  }
  return graph;
}

// Node size grows with the square root of the file's line count.
function nodeSize(lines) {
  return Math.round(16 + 2 * Math.sqrt(typeof lines === 'number' && lines > 0 ? lines : 0));
}

function toElements(graph) {
  const parents = graph.families.map((f) => ({
    group: 'nodes',
    data: { id: FAMILY_PREFIX + f.id, label: f.label, kind: 'family', family: f.id },
  }));
  const nodes = graph.nodes.map((n) => ({
    group: 'nodes',
    data: {
      id: n.id,
      label: nodeLabel(n.name || n.id),
      kind: n.kind,
      measured: isMeasured(n),
      family: n.family,
      parent: FAMILY_PREFIX + n.family,
      size: nodeSize(n.lines),
    },
  }));
  const edges = graph.edges.map((e) => ({
    group: 'edges',
    data: { id: e.id, source: e.source, target: e.target, kind: e.kind },
  }));
  return parents.concat(nodes, edges);
}

// Each family gets its own cell so family boxes never overlap: cells are sized
// by member count (a near-square grid of fixed slots, one per member) and
// arranged in a grid of cells. The number of cell columns is the one that lets
// the whole graph fit the viewport at the largest zoom, which keeps labels as
// large as possible. Members are placed inside their cell by Cytoscape's
// built-in grid layout.
const SLOT = { w: 130, h: 140 };
const GAP = 50;

function placeCells(shapes, cols) {
  const colW = [];
  const rowH = [];
  shapes.forEach((s, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    colW[col] = Math.max(colW[col] || 0, s.w);
    rowH[row] = Math.max(rowH[row] || 0, s.h);
  });
  const offset = (sizes, n) => sizes.slice(0, n).reduce((sum, size) => sum + size + GAP, 0);
  return {
    w: offset(colW, colW.length) - GAP,
    h: offset(rowH, rowH.length) - GAP,
    cells: shapes.map((s, i) => ({ ...s, x1: offset(colW, i % cols), y1: offset(rowH, Math.floor(i / cols)) })),
  };
}

function familyCells(families, aspect = 1) {
  const shapes = families.map((f) => {
    const c = Math.max(1, Math.ceil(Math.sqrt(f.count)));
    const r = Math.max(1, Math.ceil(f.count / c));
    return { id: f.id, cols: c, rows: r, w: c * SLOT.w, h: r * SLOT.h };
  });
  let best = null;
  for (let cols = 1; cols <= Math.max(1, shapes.length); cols++) {
    const placed = placeCells(shapes, cols);
    const scale = Math.min(aspect / placed.w, 1 / placed.h);
    if (!best || scale > best.scale) best = { scale, cells: placed.cells };
  }
  return best.cells;
}

function layoutFamilies(cy, graph) {
  const counts = graph.families.map((f) => ({
    id: f.id,
    count: graph.nodes.filter((n) => n.family === f.id).length,
  }));
  const w = cy.width();
  const h = cy.height();
  const aspect = w > 0 && h > 0 ? w / h : 1;
  for (const cell of familyCells(counts, aspect)) {
    const members = cy.getElementById(FAMILY_PREFIX + cell.id).children();
    members
      .layout({
        name: 'grid',
        boundingBox: { x1: cell.x1, y1: cell.y1, w: cell.w, h: cell.h },
        cols: cell.cols,
        rows: cell.rows,
        sort: (a, b) => (a.id() < b.id() ? -1 : a.id() > b.id() ? 1 : 0),
        avoidOverlap: true,
        animate: false,
        fit: false,
      })
      .run();
  }
}

// Edges are straight unless a straight line would pass over a node it does not
// connect, which would read as a reference that does not exist. Such an edge is
// bent: offsets of growing size are tried on alternate sides, and each try is
// checked against the path Cytoscape actually computes for it.
const ROUTE_BENDS = [40, -40, 80, -80, 120, -120, 170, -170, 230, -230, 300, -300];
const ROUTE_CLEARANCE = 6;

function edgePath(edge, steps = 40) {
  const s = edge.sourceEndpoint();
  const t = edge.targetEndpoint();
  const cps = edge.controlPoints() || [];
  const ctrl = [s, ...cps, t];
  const points = [];
  for (let i = 0; i <= steps; i++) {
    let level = ctrl;
    const u = i / steps;
    while (level.length > 1) {
      const next = [];
      for (let j = 0; j < level.length - 1; j++) {
        next.push({ x: level[j].x + u * (level[j + 1].x - level[j].x), y: level[j].y + u * (level[j + 1].y - level[j].y) });
      }
      level = next;
    }
    points.push(level[0]);
  }
  return points;
}

function edgeBlockers(edge, members, clearance = ROUTE_CLEARANCE) {
  const ends = new Set([edge.source().id(), edge.target().id()]);
  const points = edgePath(edge);
  return members.filter((n) => {
    if (ends.has(n.id())) return false;
    const q = n.position();
    const r = n.width() / 2 + clearance;
    return points.some((p) => (p.x - q.x) ** 2 + (p.y - q.y) ** 2 < r * r);
  });
}

function routeEdges(cy) {
  const members = cy.nodes().filter((n) => !n.isParent());
  const unrouted = [];
  cy.edges().forEach((edge) => {
    if (edgeBlockers(edge, members).length === 0) return;
    for (const bend of ROUTE_BENDS) {
      edge.style({ 'curve-style': 'unbundled-bezier', 'control-point-distances': bend, 'control-point-weights': 0.5 });
      if (edgeBlockers(edge, members).length === 0) {
        edge.data('bend', bend);
        return;
      }
    }
    edge.removeStyle('curve-style control-point-distances control-point-weights');
    unrouted.push(edge.id());
  });
  return unrouted;
}

function nodeDetails(graph, id) {
  const node = graph.nodes.find((n) => n.id === id);
  if (!node) return null;
  const family = graph.families.find((f) => f.id === node.family);
  return {
    node,
    familyLabel: family ? family.label : node.family,
    outgoing: graph.edges.filter((e) => e.source === id),
    incoming: graph.edges.filter((e) => e.target === id),
  };
}

if (typeof module === 'object' && module.exports) {
  module.exports = {
    checkGraph,
    nodeSize,
    toElements,
    nodeDetails,
    familyCells,
    layoutFamilies,
    isMeasured,
    nodeLabel,
    edgePath,
    edgeBlockers,
    routeEdges,
    FAMILY_PREFIX,
    KIND_COLORS,
    MEASURED_OUTLINE,
    LABEL_FONT_SIZE,
    SLOT,
  };
}

if (typeof document !== 'undefined') {
  main();
}

function main() {
  const statusEl = document.getElementById('status');
  const detailsEl = document.getElementById('details');
  const filtersEl = document.getElementById('filters');
  const edgeFiltersEl = document.getElementById('edge-filters');
  const legendEl = document.getElementById('legend');

  function fail(message) {
    statusEl.textContent = message;
    window.__graphError = message;
  }

  if (typeof window.cytoscape !== 'function') {
    fail('Cytoscape.js did not load (vendor/cytoscape.min.js).');
    return;
  }

  fetch('data/graph.json')
    .then((res) => {
      if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
      return res.json();
    })
    .then((graph) => render(checkGraph(graph)))
    .catch((err) => fail(`Could not load data/graph.json: ${err.message}`));

  function el(tag, text) {
    const node = document.createElement(tag);
    if (text !== undefined) node.textContent = text;
    return node;
  }

  function field(dl, term, value) {
    if (value === undefined || value === null || value === '') return;
    dl.append(el('dt', term), el('dd', String(value)));
  }

  function edgeList(title, edges, graph, end) {
    const section = el('section');
    section.append(el('h3', `${title} (${edges.length})`));
    if (edges.length === 0) {
      section.append(el('p', 'none'));
      return section;
    }
    const list = el('ul');
    for (const e of edges) {
      const other = graph.nodes.find((n) => n.id === e[end]);
      const name = other ? other.name || other.id : e[end];
      const where = Array.isArray(e.lines) ? e.lines.join(', ') : e.line;
      list.append(el('li', `${name} (${e.kind}), ${e.file}:${where}`));
    }
    section.append(list);
    return section;
  }

  function showDetails(graph, id) {
    const info = nodeDetails(graph, id);
    detailsEl.replaceChildren();
    detailsEl.dataset.nodeId = id;
    if (!info) {
      detailsEl.append(el('p', `No data for ${id}.`));
      return;
    }
    const n = info.node;
    detailsEl.append(el('h2', n.name || n.id));
    const dl = el('dl');
    field(dl, 'Kind', n.kind);
    field(dl, 'Family', info.familyLabel);
    field(dl, 'Description', n.description);
    field(dl, 'Path', n.path);
    field(dl, 'Lines', n.lines);
    if (n.origin) {
      const where = n.origin.from === 'body' ? `${n.path}:${n.origin.line}` : 'frontmatter license field';
      field(dl, 'License origin', [n.origin.text, n.origin.license && `license ${n.origin.license}`, `(${where})`].filter(Boolean).join(' '));
    } else {
      field(dl, 'License origin', 'not stated in the file');
    }
    if (n.license_notice) {
      field(dl, 'License notice', `${n.license_notice.text} (${n.license_notice.file}:${n.license_notice.line})`);
    }
    if (n.kind === 'skill') {
      field(dl, 'Eval status', n.eval_line ? `${n.eval_status} (${n.path}:${n.eval_line})` : n.eval_status);
    }
    if (Array.isArray(n.coverage)) {
      field(dl, 'Hook coverage', n.coverage.map((c) => `${c.event} ${c.matcher || '(all tools)'}`).join('; '));
    }
    detailsEl.append(dl);
    detailsEl.append(edgeList('Outgoing', info.outgoing, graph, 'target'));
    detailsEl.append(edgeList('Incoming', info.incoming, graph, 'source'));
  }

  function renderLegend(graph) {
    legendEl.replaceChildren(el('h2', 'Legend'));
    const list = el('ul');
    for (const [kind, color] of Object.entries(KIND_COLORS)) {
      const swatch = el('span');
      swatch.className = 'swatch';
      swatch.dataset.kind = kind;
      swatch.style.backgroundColor = color;
      const count = graph.nodes.filter((n) => n.kind === kind).length;
      const item = el('li');
      item.append(swatch, `${kind} (${count})`);
      list.append(item);
    }
    const outline = el('span');
    outline.className = 'swatch outline';
    outline.style.border = `${MEASURED_OUTLINE.width}px solid ${MEASURED_OUTLINE.color}`;
    const measured = graph.nodes.filter(isMeasured).length;
    const outlineItem = el('li');
    outlineItem.append(outline, `outline: an eval score stated in the skill's own SKILL.md (${measured} ${measured === 1 ? 'node' : 'nodes'})`);
    list.append(outlineItem);
    const lines = graph.nodes.map((n) => n.lines).filter((n) => typeof n === 'number');
    list.append(
      el('li', `Node size: grows with the square root of the file's line count (${Math.min(...lines)} to ${Math.max(...lines)} lines here).`),
      el('li', 'Arrow: from the file that names another node to the node it names.'),
      el('li', 'Boxes: families, from viz/scripts/families.json.'),
    );
    legendEl.append(list);
  }

  function render(graph) {
    statusEl.textContent =
      `${graph.nodes.length} nodes, ${graph.edges.length} edges, ${graph.families.length} families, ` +
      `generated by ${graph.generated_by || 'an unknown script'}.`;

    const cy = window.cytoscape({
      container: document.getElementById('graph'),
      elements: toElements(graph),
      style: [
        {
          selector: 'node',
          style: {
            label: 'data(label)',
            'font-family': 'system-ui, sans-serif',
            'font-size': LABEL_FONT_SIZE,
            'text-valign': 'bottom',
            'text-margin-y': 4,
            'text-wrap': 'wrap',
            'text-max-width': `${SLOT.w - 10}px`,
          },
        },
        { selector: 'node[size]', style: { width: 'data(size)', height: 'data(size)' } },
        ...Object.entries(KIND_COLORS).map(([kind, color]) => ({
          selector: `node[kind = "${kind}"]`,
          style: { 'background-color': color },
        })),
        {
          selector: 'node[?measured]',
          style: {
            'border-width': MEASURED_OUTLINE.width,
            'border-color': MEASURED_OUTLINE.color,
            'text-margin-y': 4 + MEASURED_OUTLINE.width,
          },
        },
        { selector: ':parent', style: { 'text-valign': 'top', 'text-margin-y': -4 } },
        { selector: 'edge', style: { 'curve-style': 'bezier', 'target-arrow-shape': 'triangle' } },
        { selector: '.filtered', style: { display: 'none' } },
      ],
    });
    window.cy = cy;
    renderLegend(graph);

    cy.on('tap', 'node', (evt) => {
      const node = evt.target;
      if (node.data('kind') !== 'family') showDetails(graph, node.id());
    });

    function addFilter(container, value, text, members) {
      const box = el('input');
      box.type = 'checkbox';
      box.checked = true;
      box.value = value;
      box.addEventListener('change', () => {
        const hit = members();
        if (box.checked) hit.removeClass('filtered');
        else hit.addClass('filtered');
      });
      const label = el('label');
      label.append(box, ` ${text}`);
      container.append(label);
    }

    for (const family of graph.families) {
      const count = graph.nodes.filter((n) => n.family === family.id).length;
      addFilter(filtersEl, family.id, `${family.label} (${count})`, () =>
        cy.nodes().filter((n) => n.data('family') === family.id),
      );
    }

    const kinds = [...new Set(graph.edges.map((e) => e.kind))].sort();
    for (const kind of kinds) {
      const count = graph.edges.filter((e) => e.kind === kind).length;
      addFilter(edgeFiltersEl, kind, `${kind} (${count})`, () => cy.edges().filter((e) => e.data('kind') === kind));
    }

    layoutFamilies(cy, graph);
    window.__unroutedEdges = routeEdges(cy);
    cy.fit(undefined, 20);
    window.__graphReady = true;
  }
}
